name: hello world
on: 
  push:
    branches: [main]
jobs:
  say-hello:
   runs-on: ubuntu-20.04
   steps:
    - run: echo "TODAY" = $(date + %y-%m-%d)" >> $GITHUB_ENV
    - run: echo Hello World, today is $TODAY